### ISSUE TITLE
`await` is wrongly used in the README example

### ISSUE THREAD

**Issue by sallar** [exponentjs/spawn-async#2]
Hi there,

The example in the `README` file shows this usage of JS `await`:
```javascript
try {
  let {
    pid,
    output: [stdout, stderr],
    stdout,
    stderr,
    status,
    signal,
  } = await resultPromise;
}
```
Which is not correct, since `await` needs to be used in an `async` function to work:

```javascript
async function test() {
  try {
    let {
      pid,
      output: [stdout, stderr],
      stdout,
      stderr,
      status,
      signal,
    } = await resultPromise;
  }
}
```

Also when destructuring, you can't redeclare `stdout` and `stderr`.

Thank you.

**Comment by ide** [comment]
The docs are meant more to convey concepts rather than to teach JavaScript, think of them as pseudocode maybe.

**Comment by perry-mitchell** [comment]
@ide how is like pseudocode? The very first example on the readme starts as so:

```js
import spawnAsync from '@exponent/spawn-async';

let resultPromise // ...
```

Users will more than likely want to copy and paste some examples to get started, and this first example clearly shows the start of a file - it wouldn't work verbatim.

It's just a bit unclear, that's all, and could be made into a more robust example with very little work as shown above.

Also, if you're planning on making an example and writing Javascript, I for one would expect it to work if I copied it. No one will assume this is pseudocode upon first glance.

**Comment by ccheever** [comment]
I updated the README so that its wrapped in an async function now
